# version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_ctn
    ports:
      - "8080:8080"  # Port UI de Jenkins
      - "50001:50001"  # Port agent Jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
    cpu_shares: 50
    mem_limit: 2g


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: austral
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/austral
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
    # cpu_shares: 50
    # mem_limit: 2g

volumes:
  db_data:

  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  #                            E N D  O F  F I L E                           #
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#